// Shared master list of sports used by team-create / team-edit dropdowns
// (Task #499) and the per-user multi-select on Edit Profile (Task #500).
// Keep order exactly as the product team specified: Block 1 = common
// sports (alphabetical), Block 2 = additional sports (alphabetical).
export const SPORTS: readonly string[] = [
  // Block 1 — common
  "Baseball",
  "Basketball",
  "Esports",
  "Field hockey",
  "Flag football",
  "Football",
  "Golf",
  "Gymnastics",
  "Ice hockey",
  "Lacrosse",
  "Soccer",
  "Softball",
  "Swimming & diving",
  "Tennis",
  "Track & field (indoor)",
  "Track & field (outdoor)",
  "Volleyball (indoor)",
  "Wrestling",
  // Block 2 — additional
  "Acrobatics & tumbling",
  "Adapted sports (bowling, floor hockey, soccer, softball, etc.)",
  "Archery",
  "Badminton",
  "Beach/sand volleyball",
  "Bowling",
  "Competitive cheer/spirit",
  "Cross country",
  "Dance/drill team",
  "Equestrian",
  "Fencing",
  "Marching band (where sanctioned as athletics)",
  "Rifle",
  "Rowing/crew",
  "Rugby",
  "Sailing",
  "Skiing (alpine and nordic)",
  "Snowboarding",
  "Stunt",
  "Triathlon",
  "Unified sports",
  "Water polo",
  "Weightlifting",
];
