// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/kinectem/AthleteFeed.tsx": () => import("../components/mockups/kinectem/AthleteFeed.tsx"),
  "./components/mockups/kinectem/AthleteProfile.tsx": () => import("../components/mockups/kinectem/AthleteProfile.tsx"),
  "./components/mockups/kinectem/GameRecapCreator.tsx": () => import("../components/mockups/kinectem/GameRecapCreator.tsx"),
  "./components/mockups/kinectem/OrganizationPage.tsx": () => import("../components/mockups/kinectem/OrganizationPage.tsx"),
  "./components/mockups/kinectem/TeamPage.tsx": () => import("../components/mockups/kinectem/TeamPage.tsx")
};
